version: enum(1)
current_context: str()
contexts: map(include('context'))
---
context:
  bootstrap_servers: list(include('url'))
  security_protocol: enum('PLAINTEXT','SASL_PLAINTEXT','SSL','SASL_SSL', required=False)
  schema_registry: include('url', required=False)
  default_values: include('defaults', required=False)
  ssl_params: include('ssl_params', required=False)
  sasl_params: include('sasl_params', required=False)

url: regex('^(?:[a-zA-Z]+://)?(?:[a-zA-Z][a-zA-Z0-9._-]+|\d{,3}(?:\.\d{,3}){3})(?::\d+)?$')

defaults:
  num_partitions: int(required=False)
  replication_factor: int(required=False)

sasl_params:
  mechanism: enum('PLAIN','SCRAM-SHA-256','SCRAM-SHA-512')
  user: str()
  password: str()

ssl_params:
  cafile: str(required=False)
  certfile: str(required=False)
  keyfile: str(required=False)
  password: str(required=False)
