dist: xenial
language: python
cache: pip
env:
- >
  TEST_CMD="pytest tests/ --integration --cov=esque --local"
  BROKER_URL="localhost:9092"
  ZOOKEEPER_URL="localhost:2181"
  SCHEMA_REGISTRY_URL="localhost:8081"
  CONFIG_PATH="confluent-community/etc/kafka/server.properties"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE="False"
before_install:
- wget http://packages.confluent.io/archive/5.2/confluent-community-5.2.1-2.12.tar.gz -O confluent-community.tgz
- mkdir -p confluent-community && tar xzf confluent-community.tgz -C confluent-community --strip-components 1
- confluent-community/bin/zookeeper-server-start -daemon confluent-community/etc/kafka/zookeeper.properties
- bash -c "scripts/wait-for-it.sh ${ZOOKEEPER_URL} -t 60"
- bash -c "scripts/init.sh"
- confluent-community/bin/kafka-server-start -daemon confluent-community/etc/kafka/server.properties
- bash -c "scripts/wait-for-it.sh ${BROKER_URL} -t 60"
- confluent-community/bin/schema-registry-start -daemon confluent-community/etc/schema-registry/schema-registry.properties
- bash -c "scripts/wait-for-it.sh ${SCHEMA_REGISTRY_URL} -t 60"
install:
- pip install -U pip
#TODO unpin once it's more stable
- pip install coverage coveralls "poetry==1.0.0b3"
- poetry install -vvv --no-root
script:
- "$TEST_CMD"
after_success:
- coveralls
notifications:
  slack:
    rooms:
      - secure: XyYngWgCIHTAF5LNarBdEA56rJvVzm8epTf3eyw40iKZcLnn/UKOxzCO6m+oo9yers1kfrUOUfrDIYjEQJoqldTh+ocLB4O0t+y+03qkie2va/ZHP4cmRl6KpAH5jM94zJfPhBAPZ2m57B/qFuAIZZmyn8mq0FTfmksKNvDbE5e8eBVu2rLsmdRQ6hkztCncwefwDHQ19k1S5Br2O/q8qekUNQRtKeGCgia4Rk1xptN9qccWzVV8426M3FdnttNSv7gO86J7OF+t3RWoow3kzCLrFFF2A+s9/NNbCL3sc6cDIjMOx4yig2b764ApUH4VrGXGF2FbeuEly7C8mR8ciunzzOAC08xpwzTae9gics9iqp7u23q5DD3dywYwApcG3jPShShP/3zdSU+MnC9r/YM+IwZdNFPo/Wqz9eTiNs7SVwCCeWdluT4iV24bGciVIye3OCseLmR/LmNnrLsGMGyTeKSwfr08RIlIqIL+DtsdIHS7Xdl3l9wNPVxLDp2yopI/0JS/85x5snaXS3nTAFefOhrqFWOhw5NCuCjRPB2njo3tpBB25TRsr2bvaSZ5nJRk1Uh+tbzayAyNPXQmxGre5j3mR5lm00CofMj8809bdaFFHqPl+L88p0Y6gn8Jc2pFKYcguc91jQhTU9KiP/QDaUb9K/TJlW1Pe2egK50=
    on_success: change
    on_failure: always
matrix:
  include:
  - name: black
    before_install: []
    python: 3.7
    env:
    - TEST_CMD="poetry run -- black --check --verbose ."
  - name: isort
    before_install: []
    python: 3.7
    env:
      - TEST_CMD="poetry run -- isort --recursive ."
  - name: flake8
    python: 3.7
    before_install: []
    env:
    - TEST_CMD="poetry run -- flake8 esque/"
  - name: '3.6'
    python: 3.6
  - name: '3.7'
    python: 3.7
  - name: 'Test install'
    python: 3.6
    env: []
    before_install:
      - mkdir -p ~/.esque
      - touch ~/.esque/esque.cfg
      - pip install poetry
    install:
      - poetry build
    script:
      - pip install --no-cache-dir dist/esque-*.tar.gz
      - esque --recreate-config --no-verify
  - name: 'Test upload'
    python: 3.6
    env:
      - secure: "znXxvfZqJEMKlu1f78uqvdnZh9y0GAzgPbJK5mBiyQxgIAooELcQnyot811fuQ35dwv5WJv19XeyosJPPVZldUmJMZmfLOa+cxBAWonVpNYNdY6iHk8Yyeoy8V43tc8fGlyG90wiw3h3Phefb9arXPCWZTNrrFSDZZGdU8/4isxLvXUENpQlBXsmi91Q755VHIyuNm9JqpAZk5eLatiE/U35SIncuPSZVtC1B1ZIJ0Bhkf9aVNNusWdeXe2B6c2tTI/rWfFDJfHUPswE+tN2Bw04uCJz7CZDjv8gZKPklNK8noeeZGNsE4X0VFnbKBVUjTWQUPpEuIzQ6Zng/ajlSP7+OhBBLMBsHutP96FwlwT7WqU4V/nK7CajU0B+ZVM8TkEvJwxJDt3+26hc/WzyxqXqNR2qcd70vG6SvGC6JosYEZxOzxmHMYWo5Aff+HMq5Is2NrI6x2kAGJEQnGfpg6S0LGBVrye8i1vzuunZGiT0oVgae5PCt+NZrJq4JFFbkV12NcPg8agNU+LOE9fd2YZCcM9ciGr09vCPgV3kID6k5pK92Lq1mVUBWqAdYsEASbUrgHOMcebtBFoMXIzo4z970DmVFeqdHX/QC1Ofp9+JROQiI/6/6UqIme5TWyTsVLrD76lP5oYD4l5xXj5VFpxCPZjaayvuNIn/eDj1/Dc="
    before_install:
      - pip install poetry devpi-server devpi "pluggy<1,>=0.12.0"
      - devpi-server --serverdir=/tmp/devpi --init
      - devpi-server --serverdir=/tmp/devpi --start
      - scripts/wait-for-it.sh localhost:3141 -t 60
      - devpi use http://localhost:3141
      - devpi login root --password=
      - devpi index -c root/stable bases=root/pypi volatile=True
      - devpi user -m root password="root"
      - mkdir -p ${HOME}/.esque
      - touch ${HOME}/.esque/esque.cfg
      - poetry config repositories.devpi http://localhost:3141/root/stable/
    install: []
    script:
      # We force-bump the version to avoid conflicts
      - poetry version
      - export VERSION=$(sed -n -E "s/^version = \"(.+)\"/\1/p" pyproject.toml)
      - poetry build
      - poetry publish --repository devpi --username root --password root
      - pip install -i http://localhost:3141/root/stable/ --timeout 60 esque==${VERSION}
      - esque --recreate-config --no-verify
  allow_failures:
    - name: '3.8-dev'
      python: 3.8-dev

deploy:
  - provider: pypi
    user: real.digital
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION == '3.6'
      repo: real-digital/esque
    password:
      secure: L7lAviuPS2FijT/t01t0SVHuxfl3/6jcSU3anWkcJdWsa9ktujvdJ6QoX0VE+niUyAwnJ6HJUNWloG1EuuRPiaVO+vIU0t39oKtP/3KKGz6zQPme4p0tpgxvPCjxzBxlaj3zs+3KlfqT7ig5EllgLcAkyCmMpvYgpPY8pCsIY/ipZ+zzQvrA9glCQex9LPhdWH7yaHgx9eGM/dQumn9J/+/CtEkbxLpmw/WHRahCgoODFBMQjTQsVleiHZqedx7gQsSD7lqbdsUkBujawdYIrGnBVIjMdqXT7nQPbKmntKf+5GMcPdFaOqgciQYYgIRLixP1JWPoHzTvsmp0Jfmd8/4u4Eh/zLOKjdsdlNk/X2hNYae+YvKXMSwYqY33cDezsIpkvbz+Vfu3Ch97c2pmp3pSTTkcxKMqnoQJ3aqZENveCPOgfb3PSrzwYBKENaFLZ45l9eU1CPgCNNa7oX/CA1+kb1wY6AMCLW4ZxOe4I3EoUpNyn4lOIEkeOsHIB5d9DJvphd5UrFgUdnADzsnAsr38Gq+Haz9YmaXscUIRvQR27HDqCwfsSn9XPkdwImIjzhPrgM5kGXm0UPsf7nGZiYwEuB2fDTji4YneDhCF4aCKzr7Txlo1BtWp5ue6kbjCARBkwgCO/uHkl8AYos/tUmZe6vl6p3kwYf8sl3i9bOs=
