version: '3.1'
services:
  esque:
    build: .
    volumes:
      - .:/esque
    environment:
      ESQUE_TEST_ENV: "ci"
    depends_on:
      - kafka
      - schema_registry
    command: >-
      -c "
        until kcat -b kafka:9093 -X debug=all -L; do
          echo 'Waiting for Kafka...';
          sleep 5;
        done;
        python3 -u -m pytest -v -x tests/ --integration
      "