version: '3'
services:
  esque:
    build: .
    volumes:
      - .:/esque
    environment:
      ESQUE_TEST_ENV: "ci"
    depends_on:
      - kafka
      - schema_registry
    command: >
      -c
        "(until (kafkacat -b kafka:9093 -X debug=all -L); do sleep 5s; done) \
        && python3 -u -m pytest -v -x tests/ --integration"