#!/bin/bash
LOGGED_USER=$USER
if [ "x$SUDO_USER" != "x" ]
then
  LOGGED_USER=$SUDO_USER
fi
USER_HOME=`cat /etc/passwd | grep "^${LOGGED_USER}:" | cut -f6 -d:`
ESQUE_CONF_DIR="${USER_HOME}/.esque"
AUTOCOMPLETION_SCRIPT="${ESQUE_CONF_DIR}/autocompletion.sh"
SHELL_BASENAME=`basename $SHELL`
ENVIRONMENT_FILE="${USER_HOME}/.bashrc"
if [ "${SHELL_BASENAME}" == 'zsh' ]
then
  ENVIRONMENT_FILE="${USER_HOME}/.zshrc"
fi