# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hi.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 2, "", "hi.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x08hi.proto"!\n\x11HelloWorldRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"\xe5\x01\n\x12HelloWorldResponse\x12\x13\n\x0btype_string\x18\x01 \x01(\t\x12\x1c\n\x0foptional_string\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\ttype_enum\x18\x03 \x01(\x0e\x32\t.EnumType\x12\x12\n\ntype_int32\x18\x04 \x01(\x05\x12\x12\n\ntype_int64\x18\x05 \x01(\x03\x12\x1b\n\x0eoptional_int64\x18\x06 \x01(\x03H\x01\x88\x01\x01\x12\x12\n\ntype_float\x18\x07 \x01(\x02\x42\x12\n\x10_optional_stringB\x11\n\x0f_optional_int64*%\n\x08\x45numType\x12\x19\n\x15\x45NUM_TYPE_UNSPECIFIED\x10\x00\x32\x34\n\x02Hi\x12.\n\x03Get\x12\x12.HelloWorldRequest\x1a\x13.HelloWorldResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "hi_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ENUMTYPE"]._serialized_start = 279
    _globals["_ENUMTYPE"]._serialized_end = 316
    _globals["_HELLOWORLDREQUEST"]._serialized_start = 12
    _globals["_HELLOWORLDREQUEST"]._serialized_end = 45
    _globals["_HELLOWORLDRESPONSE"]._serialized_start = 48
    _globals["_HELLOWORLDRESPONSE"]._serialized_end = 277
    _globals["_HI"]._serialized_start = 318
    _globals["_HI"]._serialized_end = 370
# @@protoc_insertion_point(module_scope)
