cleanup.policy: enum('', 'compact', 'delete', 'compact,delete', 'delete,compact')
compression.type: enum('uncompressed', 'zstd', 'lz4', 'snappy', 'gzip', 'producer')
delete.retention.ms: int(min=0)
file.delete.delay.ms: int(min=0)
flush.messages: int(min=0)
flush.ms: int(min=0)
follower.replication.throttled.replicas: list() #TODO not sure if correct
index.interval.bytes: int(min=0)
leader.replication.throttled.replicas: list()
max.compaction.lag.ms: int(min=1)
max.message.bytes: int(min=0)
message.format.version: enum(
  '0.8.0',
  '0.8.1',
  '0.8.2',
  '0.9.0',
  '0.10.0-IV0',
  '0.10.0-IV1',
  '0.10.1-IV0',
  '0.10.1-IV1',
  '0.10.1-IV2',
  '0.10.2-IV0',
  '0.11.0-IV0',
  '0.11.0-IV1',
  '0.11.0-IV2',
  '1.0-IV0',
  '1.1-IV0',
  '2.0-IV0',
  '2.0-IV1',
  '2.1-IV0',
  '2.1-IV1',
  '2.1-IV2',
  '2.2-IV0',
  '2.2-IV1',
  '2.3-IV0',
  '2.3-IV1',
)
message.timestamp.difference.max.ms: int(min=0)
message.timestamp.type: enum('CreateTime', 'LogAppendTime')
min.cleanable.dirty.ratio: num(min=0, max=1)
min.compaction.lag.ms: int(min=0)
min.insync.replicas: int(min=1)
preallocate: bool()
retention.bytes: int(min=-1)
retention.ms: int(min=-1)
segment.bytes: int(min=14)
segment.index.bytes: int(min=0)
segment.jitter.ms: int(min=0)
segment.ms: int(min=1)
unclean.leader.election.enable: bool()
message.downconversion.enable: bool()
