name: Build, test and package esque
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-style:
    name: Code style check on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.x', '3.6', '3.7', 'pypy3' ]
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - uses: bulv1ne/python-style-check@master
  test-integration:
    name: Integration test with Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.x', '3.6', '3.7', 'pypy3' ]
      max-parallel: 1
    services:
      zookeeper-kafka:
        image: spotify/kafka
        ports:
          - 2181:2181
          - 9092:9092
        env:
          ZOO_MY_ID: 1
          ZOO_SERVERS: server.1=0.0.0.0:2888:3888
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
          KAFKA_ADVERTISED_PORT: 9092
      schemaregistry:
        image: confluentinc/cp-schema-registry
        ports:
          - 8081:8081
        env:
          SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: none
          SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "localhost:2181"
          SCHEMA_REGISTRY_HOST_NAME: localhost
          SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    steps:
      - uses: actions/checkout@master
      - name: Verify test environment
        run: |
          bash -c "./scripts/wait-for-it.sh ${ZOOKEEPER_URL} -t 60" ;
          bash -c "./scripts/init.sh" ;
          bash -c "./scripts/wait-for-it.sh ${BROKER_URL} -t 60" ;
          bash -c "./scripts/wait-for-it.sh ${SCHEMA_REGISTRY_URL} -t 60" ;
        env:
          ZOOKEEPER_URL: localhost:2181
          BROKER_URL: localhost:9092
          SCHEMA_REGISTRY_URL: localhost:8081
          CONFIG_PATH: "confluent-community/etc/kafka/server.properties"
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "False"
      - name: Run pytest
        run: |
          sudo apt-get install -y python3-setuptools python3-virtualenv python3-pip virtualenv python3-pytest python3-pytest-mock python3-pytest-cov
          pip3 install pytest pytest-mock pytest-cov black flake8
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3
          export PATH=$PATH:$HOME/.poetry/bin
          source $HOME/.poetry/env
          virtualenv venv --python=python3
          source ./venv/bin/activate
          pip3 install .
          poetry run pytest --integration --local tests/
#  publish-to-pypi:
#    name: Publish to pypi
#    needs: [test-style, test-integration]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: Install required packages
#        run: |
#          sudo pip3 install pep517
#          python3 -m pep517.build --source --binary --out-dir dist/
#        shell: bash
#      # secrets must be set up on GitHub
#      #- name: Publish esque to PyPI
#      #  uses: pypa/gh-action-pypi-publish@master
#      #  with:
#      #    password: ${{ secrets.pypi_password }}
